// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// junkfunction3
arma::mat junkfunction3();
RcppExport SEXP DiffusionRimp_junkfunction3() {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    __result = Rcpp::wrap(junkfunction3());
    return __result;
END_RCPP
}
